variables:
  webservice_name: dependancyindexer
stages:
- stage: terraform
  jobs:
  - job: alignment
    variables:
    - group: dg-tf-vars
    - group: dg-appsvc-vars
    steps:
    - task: AzureCLI@1
      displayName: apply
      inputs:
        azureSubscription: pipeline-dg 
        scriptLocation: inlineScript
        workingDirectory: terraform
        inlineScript: |
          terraform init -input=false -backend-config="resource_group_name=$(sa-rg)" -backend-config="storage_account_name=$(sa)" -backend-config="container_name=$(sa-container)"
          terraform plan -out=tfplan -input=false
          terraform apply tfplan
      env:
        ARM_CLIENT_ID: $(client-id)
        ARM_CLIENT_SECRET: $(client-secret)
        ARM_SUBSCRIPTION_ID: $(subscription-id)
        ARM_TENANT_ID: $(tenant-id)
        ARM_ACCESS_KEY: $(access-key)
        TF_VAR_dependency_graph_url: $(dg_websiteUrl)
        TF_VAR_dependency_graph_code: $(dg_websiteCode)
        TF_VAR_webservice_name: $(webservice_name)
